### ISSUE TITLE
Exception in SSTAF Analyzer at startup

### ISSUE THREAD

**Issue by canthurt** [DAC-SSTAF/SSTAF#6]
I am getting this exception at startup:

Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at mil.sstaf.analyzer/mil.sstaf.analyzer.Main.main(Main.java:73)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at mil.sstaf.analyzer/mil.sstaf.analyzer.Analyzer.start(Analyzer.java:205)
        at mil.sstaf.analyzer/mil.sstaf.analyzer.Main.main(Main.java:71)
Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at java.base/java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:802)
        at java.base/java.util.Map.of(Map.java:1349)
        at mil.sstaf.analyzer/mil.sstaf.analyzer.Analyzer$1.call(Analyzer.java:111)
        at mil.sstaf.analyzer/mil.sstaf.analyzer.Analyzer$1.call(Analyzer.java:60)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

Running in Windows using the batch file.

**Comment by ronaldbowers** [comment]
Integration tests for the Analyzer application do not appear to be executing during the build. If I run them manually from within IntelliJ they fail.

**Comment by ronaldbowers** [comment]
Inputs for integration tests are missing. I've restored them. Tests still fail.
