### ISSUE TITLE
JSON message throws on deserialization

### ISSUE THREAD

**Issue by ronaldbowers** [DAC-SSTAF/SSTAF#8]
I am trying to get the ANSUR command to work, but I get this exception:
 
2023-02-23 13:22:40,752 INFO SSTAFDriver.SSTAFProcess - [pool-2-thread-1] WARN mil.sstaf.analyzer.Analyzer - Exception thrown processing {"class":"mil.sstaf.analyzer.messages.CommandList","commands":[{"class":"mil.sstaf.session.messages.Command","recipientPath":"BLUE:Blue Platoon:Leader","content":{"class":"mil.devcom_sc.ansur.messages.GetValueMessage","valueKey":"GENDER"}}],"mode":"TICK","time_ms":2000}
2023-02-23 13:22:40,753 INFO SSTAFDriver.SSTAFProcess - mil.sstaf.core.util.SSTAFException: Could not convert '{"class":"mil.sstaf.analyzer.messages.CommandList","commands":[{"class":"mil.sstaf.session.messages.Command","recipientPath":"BLUE:Blue Platoon:Leader","content":{"class":"mil.devcom_sc.ansur.messages.GetValueMessage","valueKey":"GENDER"}}],"mode":"TICK","time_ms":2000}' into a BaseAnalyzerCommand
2023-02-23 13:22:40,753 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.analyzer/mil.sstaf.analyzer.JsonDeserializer.apply(JsonDeserializer.java:58)
2023-02-23 13:22:40,753 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.analyzer/mil.sstaf.analyzer.JsonDeserializer.apply(JsonDeserializer.java:31)
2023-02-23 13:22:40,753 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.analyzer/mil.sstaf.analyzer.Analyzer$1.call(Analyzer.java:129)
2023-02-23 13:22:40,753 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.analyzer/mil.sstaf.analyzer.Analyzer$1.call(Analyzer.java:60)
2023-02-23 13:22:40,753 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-23 13:22:40,754 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-02-23 13:22:40,754 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-02-23 13:22:40,754 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.lang.Thread.run(Thread.java:834)
 
Do you know what I am missing?  Looks like the command should be in valid JSON.

**Comment by canthurt** [comment]
Verified working for GetValueMessage and GetValueResponse!
