### ISSUE TITLE
EquipmentHandler does not register messages handled

### ISSUE THREAD

**Issue by canthurt** [DAC-SSTAF/SSTAF#9]
EquipmentHandler does not register for messages that it handles.  Need to update EquipmentHandler::contentHandled() to handle GetInventory, Reload, SetGun, and Shoot.

**Comment by canthurt** [comment]
Here is an example of the output from SetGun:

2023-02-24 14:56:07,564 INFO SSTAFDriver.Program - Command: {"class":"mil.sstaf.analyzer.messages.CommandList","commands":[{"class":"mil.sstaf.session.messages.Command","recipientPath":"BLUE:Blue Platoon:Leader","content":{"class":"mil.devcom_dac.equipment.messages.SetGun","gun":"M4"}}],"mode":"TICK","time_ms":4000}

2023-02-24 14:56:07,671 INFO SSTAFDriver.SSTAFProcess - [pool-1-thread-2] ERROR mil.sstaf.core.entity.FeatureManager -                                                                                                                      In Blue Platoon:Leader, No handler for message of type class mil.devcom_dac.equipment.messages.SetGun, received from mil.sstaf.core.entity.Address@a409ad45
2023-02-24 14:56:07,672 INFO SSTAFDriver.SSTAFProcess -         Types handled are [class mil.devcom_sc.ansur.messages.GetValueMessage, class mil.sstaf.blackboard.api.AddEntryRequest, class mil.sstaf.blackboard.api.GetEntryRequest, class mil.sstaf.blackboard.api.RemoveEntryRequest]
2023-02-24 14:56:07,672 INFO SSTAFDriver.SSTAFProcess -         The handlers are [Telemetry Agent 1.0.0 [CSV telemetry writer], ANSUR Anthropometry 1.0.0 [Provides ANSUR II data], Kit Manager 0.1.0 [Handler for military equipment loading], Blackboard 1.0.0 [Simple in-memory implementation of a Blackboard]]

**Comment by canthurt** [comment]
Commands are being sent, but I am having issues using them, as they all (except Reload) throw exceptions as follows:

GetInventory:
2023-02-27 12:16:58,297 INFO SSTAFDriver.Program - Command: {"class":"mil.sstaf.analyzer.messages.CommandList","commands":[{"class":"mil.sstaf.session.messages.Command","recipientPath":"BLUE:Blue Platoon:Leader","content":{"class":"mil.devcom_dac.equipment.messages.GetInventory"}}],"mode":"TICK","time_ms":3000}

2023-02-27 12:16:58,410 INFO SSTAFDriver.SSTAFProcess - [pool-1-thread-3] ERROR mil.sstaf.core.entity.BaseEntity - Entity 979949f1-45a4-4d6d-b8da-d6756a0c8ddc: {}
2023-02-27 12:16:58,411 INFO SSTAFDriver.SSTAFProcess - java.lang.NullPointerException
2023-02-27 12:16:58,411 INFO SSTAFDriver.SSTAFProcess -         at mil.devcom_dac.equipment.handler/mil.devcom_dac.equipment.handler.EquipmentHandler.buildInventory(EquipmentHandler.java:156)
2023-02-27 12:16:58,412 INFO SSTAFDriver.SSTAFProcess -         at mil.devcom_dac.equipment.handler/mil.devcom_dac.equipment.handler.EquipmentHandler.process(EquipmentHandler.java:119)
2023-02-27 12:16:58,412 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.core/mil.sstaf.core.entity.FeatureManager.process(FeatureManager.java:197)
2023-02-27 12:16:58,412 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.core/mil.sstaf.core.entity.BaseEntity.processMessages(BaseEntity.java:375)
2023-02-27 12:16:58,413 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.session/mil.sstaf.session.control.EntityController$ProcessEventsCallable.call(EntityController.java:541)
2023-02-27 12:16:58,413 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.session/mil.sstaf.session.control.EntityController$ProcessEventsCallable.call(EntityController.java:524)
2023-02-27 12:16:58,414 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-27 12:16:58,415 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-02-27 12:16:58,415 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-02-27 12:16:58,416 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.lang.Thread.run(Thread.java:834)
2023-02-27 12:16:58,417 INFO SSTAFDriver.SSTAFProcess - java.lang.NullPointerException
2023-02-27 12:16:58,418 INFO SSTAFDriver.SSTAFProcess -         at mil.devcom_dac.equipment.handler/mil.devcom_dac.equipment.handler.EquipmentHandler.buildInventory(EquipmentHandler.java:156)
2023-02-27 12:16:58,418 INFO SSTAFDriver.SSTAFProcess -         at mil.devcom_dac.equipment.handler/mil.devcom_dac.equipment.handler.EquipmentHandler.process(EquipmentHandler.java:119)
2023-02-27 12:16:58,419 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.core/mil.sstaf.core.entity.FeatureManager.process(FeatureManager.java:197)
2023-02-27 12:16:58,420 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.core/mil.sstaf.core.entity.BaseEntity.processMessages(BaseEntity.java:375)
2023-02-27 12:16:58,422 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.session/mil.sstaf.session.control.EntityController$ProcessEventsCallable.call(EntityController.java:541)
2023-02-27 12:16:58,423 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.session/mil.sstaf.session.control.EntityController$ProcessEventsCallable.call(EntityController.java:524)
2023-02-27 12:16:58,423 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-27 12:16:58,425 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-02-27 12:16:58,425 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-02-27 12:16:58,426 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.lang.Thread.run(Thread.java:834)

SetGun:
2023-02-27 12:16:58,447 INFO SSTAFDriver.Program - Command: {"class":"mil.sstaf.analyzer.messages.CommandList","commands":[{"class":"mil.sstaf.session.messages.Command","recipientPath":"BLUE:Blue Platoon:Leader","content":{"class":"mil.devcom_dac.equipment.messages.SetGun","gun":"M4"}}],"mode":"TICK","time_ms":4000}

2023-02-27 12:16:58,559 INFO SSTAFDriver.SSTAFProcess - [pool-1-thread-1] ERROR mil.sstaf.core.entity.BaseEntity - Entity 979949f1-45a4-4d6d-b8da-d6756a0c8ddc: {}
2023-02-27 12:16:58,559 INFO SSTAFDriver.SSTAFProcess - java.lang.NullPointerException
2023-02-27 12:16:58,565 INFO SSTAFDriver.SSTAFProcess -         at mil.devcom_dac.equipment.handler/mil.devcom_dac.equipment.handler.EquipmentHandler.process(EquipmentHandler.java:139)
2023-02-27 12:16:58,572 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.core/mil.sstaf.core.entity.FeatureManager.process(FeatureManager.java:197)
2023-02-27 12:16:58,572 INFO SSTAFDriver.SSTAFProcess - Sending command.
2023-02-27 12:16:58,573 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.core/mil.sstaf.core.entity.BaseEntity.processMessages(BaseEntity.java:375)
2023-02-27 12:16:58,575 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.session/mil.sstaf.session.control.EntityController$ProcessEventsCallable.call(EntityController.java:541)
2023-02-27 12:16:58,576 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.session/mil.sstaf.session.control.EntityController$ProcessEventsCallable.call(EntityController.java:524)
2023-02-27 12:16:58,576 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-27 12:16:58,577 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-02-27 12:16:58,578 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-02-27 12:16:58,578 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.lang.Thread.run(Thread.java:834)
2023-02-27 12:16:58,579 INFO SSTAFDriver.SSTAFProcess - java.lang.NullPointerException
2023-02-27 12:16:58,579 INFO SSTAFDriver.SSTAFProcess -         at mil.devcom_dac.equipment.handler/mil.devcom_dac.equipment.handler.EquipmentHandler.process(EquipmentHandler.java:139)
2023-02-27 12:16:58,580 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.core/mil.sstaf.core.entity.FeatureManager.process(FeatureManager.java:197)
2023-02-27 12:16:58,580 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.core/mil.sstaf.core.entity.BaseEntity.processMessages(BaseEntity.java:375)
2023-02-27 12:16:58,581 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.session/mil.sstaf.session.control.EntityController$ProcessEventsCallable.call(EntityController.java:541)
2023-02-27 12:16:58,581 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.session/mil.sstaf.session.control.EntityController$ProcessEventsCallable.call(EntityController.java:524)
2023-02-27 12:16:58,582 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-27 12:16:58,582 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-02-27 12:16:58,583 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-02-27 12:16:58,584 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.lang.Thread.run(Thread.java:834)

Shoot:
2023-02-27 12:16:58,574 INFO SSTAFDriver.Program - Command: {"class":"mil.sstaf.analyzer.messages.CommandList","commands":[{"class":"mil.sstaf.session.messages.Command","recipientPath":"BLUE:Blue Platoon:Leader","content":{"class":"mil.devcom_dac.equipment.messages.Shoot","gun":"M4","numToShoot":5}}],"mode":"TICK","time_ms":5000}
2023-02-27 12:16:58,682 INFO SSTAFDriver.SSTAFProcess - [pool-1-thread-16] ERROR mil.sstaf.core.entity.BaseEntity - Entity 979949f1-45a4-4d6d-b8da-d6756a0c8ddc: {}
2023-02-27 12:16:58,682 INFO SSTAFDriver.SSTAFProcess - java.lang.NullPointerException
2023-02-27 12:16:58,686 INFO SSTAFDriver.SSTAFProcess -         at mil.devcom_dac.equipment.api/mil.devcom_dac.equipment.api.Gun.shoot(Gun.java:68)
2023-02-27 12:16:58,694 INFO SSTAFDriver.SSTAFProcess - Sending command.
2023-02-27 12:16:58,694 INFO SSTAFDriver.SSTAFProcess -         at mil.devcom_dac.equipment.handler/mil.devcom_dac.equipment.handler.EquipmentHandler.process(EquipmentHandler.java:109)
2023-02-27 12:16:58,696 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.core/mil.sstaf.core.entity.FeatureManager.process(FeatureManager.java:197)
2023-02-27 12:16:58,697 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.core/mil.sstaf.core.entity.BaseEntity.processMessages(BaseEntity.java:375)
2023-02-27 12:16:58,699 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.session/mil.sstaf.session.control.EntityController$ProcessEventsCallable.call(EntityController.java:541)
2023-02-27 12:16:58,700 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.session/mil.sstaf.session.control.EntityController$ProcessEventsCallable.call(EntityController.java:524)
2023-02-27 12:16:58,700 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-27 12:16:58,701 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-02-27 12:16:58,702 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-02-27 12:16:58,702 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.lang.Thread.run(Thread.java:834)
2023-02-27 12:16:58,703 INFO SSTAFDriver.SSTAFProcess - java.lang.NullPointerException
2023-02-27 12:16:58,704 INFO SSTAFDriver.SSTAFProcess -         at mil.devcom_dac.equipment.api/mil.devcom_dac.equipment.api.Gun.shoot(Gun.java:68)
2023-02-27 12:16:58,704 INFO SSTAFDriver.SSTAFProcess -         at mil.devcom_dac.equipment.handler/mil.devcom_dac.equipment.handler.EquipmentHandler.process(EquipmentHandler.java:109)
2023-02-27 12:16:58,712 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.core/mil.sstaf.core.entity.FeatureManager.process(FeatureManager.java:197)
2023-02-27 12:16:58,716 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.core/mil.sstaf.core.entity.BaseEntity.processMessages(BaseEntity.java:375)
2023-02-27 12:16:58,717 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.session/mil.sstaf.session.control.EntityController$ProcessEventsCallable.call(EntityController.java:541)
2023-02-27 12:16:58,717 INFO SSTAFDriver.SSTAFProcess -         at mil.sstaf.session/mil.sstaf.session.control.EntityController$ProcessEventsCallable.call(EntityController.java:524)
2023-02-27 12:16:58,718 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-27 12:16:58,719 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-02-27 12:16:58,719 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-02-27 12:16:58,721 INFO SSTAFDriver.SSTAFProcess -         at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by canthurt** [comment]
Confirmed work around is to Reload first.
